### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by yzf123456** [velociraptor111/tf-deep-facial-recognition-lite#1]
Hello，
Firstly,thanks for  your code, I recently downloaded your code and tried to implement it according to the steps, but there was a problem and it has not been solved. Problem: 
TimeoutError: [WinError 10060] The connection attempt failed because the connected party did not respond correctly after a period of time or the connected host did not respond.
Looking forward to your guidance.

Best blessing

**Comment by velociraptor111** [comment]
Hey @yzf123456 , as mentioned in the readme, this repo is no longer maintained but I will try my best to help you out. 

Could you provide me with more information on what you tried to run on your script?

**Comment by yzf123456** [comment]
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/tf-deep-facial-recognition-lite-master/download_model_checkpoints.py", line 59, in <module>
    download_file_from_google_drive(file_id, zip_file_destination)
  File "C:/Users/DELL/Desktop/tf-deep-facial-recognition-lite-master/download_model_checkpoints.py", line 12, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1tdNgX1qlq_nCtGuU7BKBUIQcL5zmsawW (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002298F6B6E48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))


thank you very much.
my computer:
WIN10
anaconda-navigator   1.9.2

tensorflow                1.14.0

------------------ 原始邮件 -----------------
发件人: "Peter Tanugraha"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 晚上9:49
收件人: "velociraptor111/tf-deep-facial-recognition-lite"<tf-deep-facial-recognition-lite@noreply.github.com>;
抄送: "45度的天空"<1277650607@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [velociraptor111/tf-deep-facial-recognition-lite] TimeoutError(#1)




Hey @yzf123456 , as mentioned in the readme, this repo is no longer maintained but I will try my best to help you out.
 
Could you provide me with more information on what you tried to run on your script?

**Comment by velociraptor111** [comment]
Hey so I just tried running the code on my end and it downloaded the checkpoints correctly. Just making sure, your computer is connected to the internet right when running the script?

**Comment by yzf123456** [comment]
ok, i will try more times.Thank you!

**Comment by velociraptor111** [comment]
Here is the link to the model checkpoints, if you need to download it manually ...  https://docs.google.com/uc?id=1tdNgX1qlq_nCtGuU7BKBUIQcL5zmsawW&export=download

Closing the issue :)
